//******************************************************************************
//
//   Ce fichier permet de définir les projets dans lesquels vous travaillez.
//  En fonction de des directives de compilation, les composants ne seront pas
//  compilés de la même facon.
//
//   Marche à suivre
//       Copier-coller le fichier : YmagConf-Exemple.inc
//       Renommer le en : YmagConf.inc
//       Ouvrer le et éditer le en fonciton de vos projets (pour activer une directive de compilation
//            il suffit d'enlever le point qui est au début.
//       Si cela n'a pas déjà été fait, il faut ajouter un chemin de recherche localisant le fichier.
//
//******************************************************************************


{$DEFINE YPAREO}
{.$DEFINE MAGY}
{.$DEFINE WICRPIME}

